name: Update Content On Heroku

on:
  workflow_dispatch:
  workflow_call:
env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Redeploy Heroku
        id: redeploy_heroku
        run: |
          curl --location --request POST \
          --url 'https://<heroku-app-name>.herokuapp.com/-/clear-cache/?package=main&all-dependencies=true'