name: Update Content On Heroku

on:
  workflow_dispatch:
  workflow_call:
env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - name: Redeploy Heroku
        id: redeploy_heroku
        run: |
          curl --location --request POST \
          --url 'https://<heroku-app-name>.herokuapp.com/-/clear-cache/?package=main&all-dependencies=true'